### ISSUE TITLE
`substance restart` causes "AttributeError: 'NoneType' object has no attribute 'then'"

### ISSUE THREAD

**Issue by epenner** [turbulent/substance#4]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/dockwrkr/console.py", line 237, in main
    self.runCommand(self.cmdString)
  File "/usr/local/lib/python2.7/dist-packages/dockwrkr/console.py", line 245, in runCommand
    self.command.execute(self.commandInput)
  File "/usr/local/lib/python2.7/dist-packages/dockwrkr/console.py", line 87, in execute
    return self.main()
  File "/usr/local/lib/python2.7/dist-packages/dockwrkr/command/restart.py", line 20, in main
    return self.core.restart(self.args, all=self.getOption('allc'), time=self.getOption('time')) \
  File "/usr/local/lib/python2.7/dist-packages/dockwrkr/core.py", line 123, in restart
    return self.__command(self.__restart, containers=containers, all=all, time=time)
  File "/usr/local/lib/python2.7/dist-packages/dockwrkr/core.py", line 200, in __command
    .bind(func, containers=containers, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dockwrkr/monads.py", line 163, in bind
    return mf(self.getOK(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dockwrkr/core.py", line 302, in __restart
    .bind(dinfo("'%s' has been started." % container))) \
AttributeError: 'NoneType' object has no attribute 'then'

Error running command restart: 'NoneType' object has no attribute 'then'
 (ShellCommandError)
An error occured when running command. (LinkCommandError)
```

**Comment by bbeausej** [comment]
What's the command line that generated this error?

**Comment by epenner** [comment]
It was `substance restart` but after testing in 0.13 it is now fixed.
